In [ ]:
#1. Importa el paquete NUMPY bajo el nombre np.

In [7]:
import numpy as np

In [9]:
#2. Imprime la versión de NUMPY y la configuración.
print(np.version.version)

1.26.4


In [45]:
#3. Genera un array tridimensional de 2x3x5 con valores aleatorios. Asigna el array a la variable "a"
a = np.random.random((2, 3, 5))
print(f"El array llamado a es:  \n{a}")

El array llamado a es:  
[[[0.46179172 0.88183129 0.79790059 0.96137263 0.22973684]
  [0.5988349  0.99480594 0.17721275 0.07954599 0.40730953]
  [0.6250159  0.99082153 0.48029938 0.63750985 0.31699168]]

 [[0.91473657 0.86897272 0.36617395 0.02065339 0.85048542]
  [0.74573528 0.61056671 0.47794436 0.46983559 0.1296528 ]
  [0.51827737 0.09620484 0.92168338 0.62438892 0.6695454 ]]]


In [59]:
#5. Crea un array tridimensional de 5x2x3 con todos los valores igual a 1.
#Asigna el array a la variable "b"

b = np.ones((5, 2, 3),dtype=int)
#6. Imprime b.
print(f"El array llamado a es:  \n{b}")

El array llamado a es:  
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [61]:
#7. ¿Tienen a y b el mismo tamaño? ¿Cómo lo demuestras en código Python?
np.size(a) == np.size(b)

True

In [69]:
#8. ¿Es posible sumar a y b? ¿Por qué sí o por qué no?
    #c = a + b
#ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
try: 
    a + b
except ValueError:
    print("a y b no se pueden sumar porque no tienen la misma forma")
# No se pueden sumar porque no tienen la misma forma

a y b no se pueden sumar porque no tienen la misma forma


In [ ]:
#9. Transpone b para que tenga la misma estructura que a (es decir, se convierta en un array de 2x3x5). Asigna el array transpuesto a la variable "c".

In [79]:
c = np.transpose(b)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [85]:
#10. Intenta sumar a y c. Ahora debería funcionar. Asigna la suma a la variable "d". Pero, ¿por qué funciona ahora?
d = a + c
# Con el tipeo incial tampoco se puede ya que aunque se transponga b, siguen quedando con forma diferente (2,3,5) (3,2,5).
# Suponemos que fue un error de tipeo y que la creacion deberia crearse como 5, 3, 2.

ValueError: operands could not be broadcast together with shapes (2,3,5) (3,2,5) 

In [87]:
b = np.ones((5, 3, 2),dtype=int)

In [89]:
c = np.transpose(b)
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [93]:
d = a + c
d

#Ahora si se pueden sumar porque tienen la misma forma.

array([[[1.46179172, 1.88183129, 1.79790059, 1.96137263, 1.22973684],
        [1.5988349 , 1.99480594, 1.17721275, 1.07954599, 1.40730953],
        [1.6250159 , 1.99082153, 1.48029938, 1.63750985, 1.31699168]],

       [[1.91473657, 1.86897272, 1.36617395, 1.02065339, 1.85048542],
        [1.74573528, 1.61056671, 1.47794436, 1.46983559, 1.1296528 ],
        [1.51827737, 1.09620484, 1.92168338, 1.62438892, 1.6695454 ]]])

In [103]:
#11. Imprime a y d. ¿Notas la diferencia y la relación entre los dos arrays en términos de los valores? Explica.

print(a)
print("-----------------------------------------------------------")
print(d)

# A los valores de "a" se le agrego un 1, que eran los valores de "b"/"c", resultando en los valores de "d".

[[[0.46179172 0.88183129 0.79790059 0.96137263 0.22973684]
  [0.5988349  0.99480594 0.17721275 0.07954599 0.40730953]
  [0.6250159  0.99082153 0.48029938 0.63750985 0.31699168]]

 [[0.91473657 0.86897272 0.36617395 0.02065339 0.85048542]
  [0.74573528 0.61056671 0.47794436 0.46983559 0.1296528 ]
  [0.51827737 0.09620484 0.92168338 0.62438892 0.6695454 ]]]
-----------------------------------------------------------
[[[1.46179172 1.88183129 1.79790059 1.96137263 1.22973684]
  [1.5988349  1.99480594 1.17721275 1.07954599 1.40730953]
  [1.6250159  1.99082153 1.48029938 1.63750985 1.31699168]]

 [[1.91473657 1.86897272 1.36617395 1.02065339 1.85048542]
  [1.74573528 1.61056671 1.47794436 1.46983559 1.1296528 ]
  [1.51827737 1.09620484 1.92168338 1.62438892 1.6695454 ]]]


In [115]:
#12. Multiplica a y c. Asigna el resultado a e.
e = a * c
print (e)
#13. ¿Es e igual a a? ¿Por qué sí o por qué no?

print(np.array_equal(e,a))
e == a

# Si, es igual a "a" ya que todo numero multiplicado por 1 es igual a su valor.

[[[0.46179172 0.88183129 0.79790059 0.96137263 0.22973684]
  [0.5988349  0.99480594 0.17721275 0.07954599 0.40730953]
  [0.6250159  0.99082153 0.48029938 0.63750985 0.31699168]]

 [[0.91473657 0.86897272 0.36617395 0.02065339 0.85048542]
  [0.74573528 0.61056671 0.47794436 0.46983559 0.1296528 ]
  [0.51827737 0.09620484 0.92168338 0.62438892 0.6695454 ]]]
True


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [117]:
#14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"

d_max = np.max(d)
print(f"d_max es igual a {d_max}")
d_min = np.min(d)
print(f"d_min es igual a {d_min}")
d_mean = np.mean(d)
print(f"d_mean es igual a {d_mean}")

d_max es igual a 1.9948059416677817
d_min es igual a 1.0206533862233806
d_mean es igual a 1.5641945726965365


In [147]:
#15. Ahora queremos etiquetar los valores en d. Primero crea un array vacío "f" con la misma forma (es decir, 2x3x5) que d usando `np.empty`.

f = np.empty_like(d)
f

array([[[0.46179172, 0.88183129, 0.79790059, 0.96137263, 0.22973684],
        [0.5988349 , 0.99480594, 0.17721275, 0.07954599, 0.40730953],
        [0.6250159 , 0.99082153, 0.48029938, 0.63750985, 0.31699168]],

       [[0.91473657, 0.86897272, 0.36617395, 0.02065339, 0.85048542],
        [0.74573528, 0.61056671, 0.47794436, 0.46983559, 0.1296528 ],
        [0.51827737, 0.09620484, 0.92168338, 0.62438892, 0.6695454 ]]])

In [157]:
#16. Rellena los valores en f. Para cada valor en d, si es mayor que d_min pero menor que d_mean, asigna 25 al valor correspondiente en f.
#Si un valor en d es mayor que d_mean pero menor que d_max, asigna 75 al valor correspondiente en f.
#Si un valor es igual a d_mean, asigna 50 al valor correspondiente en f.
#Asigna 0 al valor correspondiente(s) en f para d_min en d.
#Asigna 100 al valor correspondiente(s) en f para d_max en d.
#Al final, f debería tener solo los siguientes valores: 0, 25, 50, 75 y 100.
#Nota: no necesitas usar Numpy en esta pregunta.

#d_min<25<d_mean
#d_min<75<d_max
#d_mean == 50
#d_min == 0
#d_max == 100

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            value = d[i][j][k]
            if d_min < value < d_mean:
                f[i][j][k] = 25
            elif d_mean < value < d_max:
                f[i][j][k] = 75
            elif value == d_mean:
                f[i][j][k] = 50
            elif value == d_min:
                f[i][j][k] = 0
            elif value == d_max:
                f[i][j][k] = 100

print(f)

[[[ 25.  75.  75.  75.  25.]
  [ 75. 100.  25.  25.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  25.   0.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  75.  75.]]]


In [171]:
#17. Imprime d y f. ¿Tienes el f esperado?
print(d)
print("-----------------------------------------------------------------")
print(f"Si {d_min} < i < {d_mean}, i = 25")
print(f"Si {d_mean} < i < {d_max}, i = 75")
print(f"Si {d_min} = i = 0")
print(f"Si {d_mean} = i = 50")
print(f"Si {d_max} = i = 100")
print("-----------------------------------------------------------------")
print(f)



[[[1.46179172 1.88183129 1.79790059 1.96137263 1.22973684]
  [1.5988349  1.99480594 1.17721275 1.07954599 1.40730953]
  [1.6250159  1.99082153 1.48029938 1.63750985 1.31699168]]

 [[1.91473657 1.86897272 1.36617395 1.02065339 1.85048542]
  [1.74573528 1.61056671 1.47794436 1.46983559 1.1296528 ]
  [1.51827737 1.09620484 1.92168338 1.62438892 1.6695454 ]]]
-----------------------------------------------------------------
Si 1.0206533862233806 < i < 1.5641945726965365, i = 25
Si 1.5641945726965365 < i < 1.9948059416677817, i = 75
Si 1.0206533862233806 = i = 0
Si 1.5641945726965365 = i = 50
Si 1.9948059416677817 = i = 100
-----------------------------------------------------------------
[[[ 25.  75.  75.  75.  25.]
  [ 75. 100.  25.  25.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  25.   0.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  75.  75.]]]


In [187]:
#18. Pregunta de bonificación: en lugar de usar números (es decir, 0, 25, 50, 75 y 100), ¿cómo usar valores de cadena 
#("A", "B", "C", "D" y "E") para etiquetar los elementos del array? Esperas el resultado sea:
e = np.empty_like((d),dtype=str)
e

for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            value = d[i][j][k]
            if d_min < value < d_mean:
                e[i][j][k] = "B"
            elif d_mean < value < d_max:
                e[i][j][k] = "D"
            elif value == d_mean:
                e[i][j][k] = "C"
            elif value == d_min:
                e[i][j][k] = "A"
            elif value == d_max:
                e[i][j][k] = "E"

print(e)

[[['B' 'D' 'D' 'D' 'B']
  ['D' 'E' 'B' 'B' 'B']
  ['D' 'D' 'B' 'D' 'B']]

 [['D' 'D' 'B' 'A' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['B' 'B' 'D' 'D' 'D']]]


In [179]:
#14. Identifica los valores máximos, mínimos y medios en d. Asigna esos valores a las variables "d_max", "d_min" y "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean (d)

print(d_max)
print(d_min)
print(d_mean)

1.9948059416677817
1.0206533862233806
1.5641945726965365
